/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Get the KREN library version. */
export declare function version(): string
/**
 * Writer endpoint for a KREN shared memory channel.
 *
 * Creates a new shared memory segment that can be connected to by readers.
 * Only one writer should exist per channel (Single-Producer constraint).
 */
export declare class Writer {
  /**
   * Create a new KREN channel.
   *
   * @param name - Unique identifier for the channel
   * @param capacity - Size of the ring buffer in bytes
   * @returns A new Writer instance
   * @throws Error if capacity is invalid or shared memory creation fails
   */
  constructor(name: string, capacity: number)
  /**
   * Write data to the channel.
   *
   * @param data - Buffer to write
   * @returns Number of bytes written
   * @throws Error if buffer is full or data is too large
   */
  write(data: Buffer): number
  /** Get the amount of free space in the buffer. */
  get available(): number
  /** Get the channel name. */
  get name(): string
}
/**
 * Reader endpoint for a KREN shared memory channel.
 *
 * Connects to an existing shared memory segment created by a writer.
 * Only one reader should exist per channel (Single-Consumer constraint).
 */
export declare class Reader {
  /**
   * Connect to an existing KREN channel.
   *
   * @param name - Name of the channel to connect to
   * @returns A new Reader instance
   * @throws Error if channel doesn't exist or connection fails
   */
  constructor(name: string)
  /**
   * Read data from the channel.
   *
   * @returns Buffer containing the read data
   * @throws Error if buffer is empty or channel is closed
   */
  read(): Buffer
  /**
   * Try to read data without blocking.
   *
   * @returns Buffer if data is available, null otherwise
   * @throws Error if channel error occurs (not including empty buffer)
   */
  tryRead(): Buffer | null
  /** Check if the writer has closed the channel. */
  get writerClosed(): boolean
  /** Get the amount of data available to read. */
  get available(): number
  /** Get the channel name. */
  get name(): string
}
